import styles from "./page.module.scss";

export const metadata = {
  title: 'WidgetEditor',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={styles.html} lang="en">
      <body className={styles.body}>{children}</body>
    </html>
  )
}
